/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stringcalculator;

import java.util.Scanner;

public class App {

    private static final Scanner scanner = new Scanner(System.in);

    public static void main(String[] args) {
        new App().run();
    }

    private void run() {
        while (true) {
            String input = getInput();

            if (input.equalsIgnoreCase("EXIT")) {
                break;
            }

            try {
                System.out.println(new Expression(input).evaluate());
            } catch (Exception e) {
                printErrorMessage(e);
            }
        }
        scanner.close();
    }

    private void printErrorMessage(Exception e) {
        System.out.println(e.getMessage());
        System.out.println();
    }

    private String getInput() {
        System.out.print("식을 입력하세요(종료를 원할 경우 EXIT 을 입력하세요 ): ");
        return scanner.nextLine();
    }
}
